"""migration3

Revision ID: 0c3ee1cb06e8
Revises: 
Create Date: 2023-09-24 11:37:00.512859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c3ee1cb06e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_map', sa.Column('original', sa.String(length=256), nullable=True))
    op.add_column('url_map', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_url_map_timestamp'), 'url_map', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_map_timestamp'), table_name='url_map')
    op.drop_column('url_map', 'timestamp')
    op.drop_column('url_map', 'original')
    # ### end Alembic commands ###
